### ISSUE TITLE
wsusserver::approvalrule: Allow removal of rule without additional information

### ISSUE THREAD

**Issue by jblance** [TraGicCode/tragiccode-wsusserver#9]
The documentation lists the below as the format to remove an approval rule
```
wsusserver::approvalrule { 'Default Automatic Approval Rule':
    ensure => 'absent'
}
```

This doesn't work, as at catalog creation an error occurs about required parameters, namely the requirements are:
```
wsusserver::approvalrule { 'Default Automatic Approval Rule':
    ensure          => 'absent',
    classifications => [],
    products        => [],
    computer_groups => [],
  }
```
It would be good to not need the classifications, products and computer_groups for rule removal

Thanks

**Comment by jblance** [comment]
I think this can be done by adding defaults to the approval rule..
``` 
define wsusserver::approvalrule (
    Array[String] $classifications = [], # Critical update, security update...etc
    Array[String] $products = [],
    Array[String] $computer_groups = [],
...
```

**Comment by TraGicCode** [comment]
I'm currently in the process of converting this defined type to a custom type and provider.  This would solve this annoying issue with the defined type since when you pass in absent for ensure all parameters are ignored.  

In the meantime we could conjure up a patch for the defined type.  I would prefer not specifying defaults that are empty arrays and opt for something like this.

```puppet
define wsusserver::approvalrule (
    Optional[Array[String]] $classifications = undef, # Critical update, security update...etc
    Optional[Array[String]] $products = undef,
    Optional[Array[String]] $computer_groups = undef,
)
```

Then there would be some sort of validation saying if ensure = present then make sure those parameters are not undefined.
